Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 25, in asyncly_list_chats
    window['-CHATS-'].update(chats)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 2575, in update
    self.TKListbox.delete(0, 'end')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3179, in delete
    self.tk.call(self._w, 'delete', first, last)
_tkinter.TclError: invalid command name ".!toplevel4.!frame2.!frame.!listbox"
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 18, in asyncly_display_chat
    window['-MESSAGES-'].update(messages)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 3446, in update
    starting_point = self.Widget.index(tk.INSERT)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3738, in index
    return str(self.tk.call(self._w, 'index', index))
_tkinter.TclError: invalid command name ".!toplevel5Exception in thread ThrException in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 25, in asyncly_list_chats
    window['-CHATS-'].update(chats)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 2575, in update
    self.TKListbox.delete(0, 'end')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3179, in delete
    self.tk.call(self._w, 'delete', first, last)
_tkinter.TclError: invalid command name ".!toplevel6.!frame2.!frame.!listbox"
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 18, in asyncly_display_chat
    window['-MESSAGES-'].update(messages)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 3446, in update
    starting_point = self.Widget.index(tk.INSERT)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3738, in index
    return str(self.tk.call(self._w, 'index', index))
_tkinter.TclError: invalid command name ".!toplevel7.!frame2.!frame.!text"
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 25, in asyncly_list_chats
    window['-CHATS-'].update(chats)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 2575, in update
    self.TKListbox.delete(0, 'end')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3179, in delete
    self.tk.call(self._w, 'delete', first, last)
RuntimeError: main thread is not in main loop
toplevel10Exception in thread ThrException in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 25, in asyncly_list_chats
    window['-CHATS-'].update(chats)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 2575, in update
    self.TKListbox.delete(0, 'end')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3179, in delete
    self.tk.call(self._w, 'delete', first, last)
_tkinter.TclError: invalid command name ".!toplevel11.!frame2.!frame.!listbox"
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 18, in asyncly_display_chat
    window['-MESSAGES-'].update(messages)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 3446, in update
    starting_point = self.Widget.index(tk.INSERT)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3738, in index
    return str(self.tk.call(self._w, 'index', index))
_tkinter.TclError: invalid command name ".!toplevel12Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 18, in asyncly_display_chat
    window['-MESSAGES-'].update(messages)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 3446, in update
    starting_point = self.Widget.index(tk.INSERT)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3738, in index
    return str(self.tk.call(self._w, 'index', index))
RuntimeError: main thread is not in main loop
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 25, in asyncly_list_chats
    window['-CHATS-'].update(chats)
  File "/home/achyut/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 2575, in update
    self.TKListbox.delete(0, 'end')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3179, in delete
    self.tk.call(self._w, 'delete', first, last)
RuntimeError: main thread is not in main loop
